# Generated by Django 3.0.6 on 2020-12-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SRPCREACTFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=50)),
                ('weekNo', models.CharField(default=None, max_length=50)),
                ('image_url', models.URLField(default=None)),
            ],
            options={
                'db_table': 'SRPC_REACT_Files',
            },
        ),
    ]
