# Generated by Django 3.0.6 on 2020-12-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REACT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(default=None, max_length=15)),
                ('Week_no', models.CharField(default=None, max_length=15)),
                ('Consider_Week_no', models.CharField(default=None, max_length=10)),
                ('Week_startdate', models.DateField(default=None)),
                ('Week_enddate', models.DateField(default=None)),
                ('Revision_no', models.CharField(default=None, max_length=255)),
                ('Letter_refno', models.CharField(default=None, max_length=255)),
                ('Letter_date', models.DateField(default=None)),
                ('Payment_date', models.DateField(default=None)),
                ('Disbursement_date', models.DateField(default=None)),
                ('Lc_date', models.DateField(default=None)),
                ('Interest_levydate', models.DateField(default=None)),
                ('Entity', models.CharField(default=None, max_length=255)),
                ('DevFinal', models.BigIntegerField(blank=True, default=None)),
                ('Outstandings', models.BigIntegerField(blank=True, default=0)),
                ('Status', models.CharField(default='Notified', max_length=100)),
                ('PayableorReceivable', models.CharField(default=None, max_length=25)),
                ('image_url', models.URLField(default='null')),
                ('modified_remarks', models.CharField(default=None, max_length=255)),
                ('registration_id', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
