# Generated by Django 3.0.6 on 2020-12-31 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REACT', '0004_auto_20201221_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='RePaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_type', models.CharField(default=None, max_length=15)),
                ('Pay_refno', models.CharField(default=None, max_length=100)),
                ('Pay_date', models.DateField(default=None)),
                ('Pay_amount', models.BigIntegerField(default=None)),
                ('Dev_final', models.BigIntegerField(default=None)),
                ('Due_amount', models.BigIntegerField(default=None)),
                ('Paid_by', models.CharField(default=None, max_length=250)),
                ('Paid_for', models.CharField(default=None, max_length=250)),
                ('Remarks', models.CharField(default=None, max_length=100)),
                ('Status', models.CharField(default='Created', max_length=50)),
                ('reject_remarks', models.CharField(default=None, max_length=255)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REACT.ReactBaseData')),
            ],
        ),
    ]
