# Generated by Django 3.0.6 on 2020-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REACT', '0005_repaymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentstatus',
            name='reject_remarks',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
