# Generated by Django 3.0.6 on 2021-01-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REACT', '0007_reactduepool'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactDisbursedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=20)),
                ('weekno', models.CharField(default=None, max_length=20)),
                ('disbursed_date', models.DateField(blank=True, default=None)),
            ],
        ),
    ]
