# Generated by Django 3.1.5 on 2021-03-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20210107_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(default=None, max_length=255)),
                ('designation', models.CharField(default=None, max_length=255)),
                ('telephone', models.BigIntegerField(blank=True, default=None)),
                ('contactName2', models.CharField(default=None, max_length=255)),
                ('designation2', models.CharField(default=None, max_length=255)),
                ('telephone2', models.BigIntegerField(blank=True, default=None)),
                ('contactName3', models.CharField(blank=True, default=None, max_length=255)),
                ('designation3', models.CharField(blank=True, default=None, max_length=255)),
                ('telephone3', models.BigIntegerField(blank=True, default=None)),
                ('register_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.formdata')),
            ],
        ),
    ]
