# Generated by Django 3.1.5 on 2021-03-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contactName3',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='designation3',
            field=models.CharField(default='NUL', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='telephone3',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
