# Generated by Django 3.1.5 on 2021-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20210304_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contactName3',
            field=models.CharField(default='NULL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='designation3',
            field=models.CharField(default='NULL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='telephone3',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
