# Generated by Django 3.1.5 on 2021-03-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_auto_20210304_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='contactName',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='contactName2',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='contactName3',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='designation2',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='designation3',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='telephone2',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='telephone3',
        ),
    ]
