# Generated by Django 3.1.5 on 2021-03-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_auto_20210304_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankpandetails',
            old_name='register_id',
            new_name='bpregister_id',
        ),
    ]
