# Generated by Django 3.1.5 on 2021-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_regapproveauthority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='isFinanceApproved',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='isFinanceVerified',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='remarks',
        ),
        migrations.AddField(
            model_name='formdata',
            name='auth1_remarks',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='auth2_remarks',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='created_by',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='review_auth1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='review_auth2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='status',
            field=models.IntegerField(default=None),
        ),
    ]
