# Generated by Django 3.1.5 on 2021-03-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_auto_20210305_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegApproveAuthority',
        ),
    ]
