# Generated by Django 3.1.5 on 2021-03-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0013_remove_formdata_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='reject_remarks1',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='reject_remarks2',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
