# Generated by Django 3.1.5 on 2021-03-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0015_formdata_latest_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='modified_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='latest_record',
            field=models.DateTimeField(default='2021-03-08 14:05:56.101614', null=True),
        ),
    ]
