# Generated by Django 3.1.5 on 2021-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0016_auto_20210308_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser1',
            name='designation',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeuser1',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeuser1',
            name='empno',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeuser1',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='latest_record',
            field=models.DateTimeField(default='2021-03-16 16:19:12.949803', null=True),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='alias1',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='alias2',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='alias3',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='alias4',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='email',
            field=models.CharField(default='test@test.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='fullname',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='shortname',
            field=models.CharField(blank=True, default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='usercategory',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='generalentities1',
            name='usertype',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
