# Generated by Django 3.0.6 on 2020-12-15 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(default=None, max_length=15)),
                ('Week_no', models.IntegerField(default=None)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('review_auth1', models.CharField(default=None, max_length=100)),
                ('review_auth2', models.CharField(default=None, max_length=100)),
                ('remarks', models.CharField(default='Null', max_length=100)),
                ('status', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ApproveAuthorityPreviousWeeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(default=None, max_length=15)),
                ('Week_no', models.IntegerField(default=None)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('review_auth1', models.CharField(default=None, max_length=100)),
                ('review_auth2', models.CharField(default=None, max_length=100)),
                ('remarks', models.CharField(default='Null', max_length=100)),
                ('status', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ChatAllMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='null', max_length=50)),
                ('sender', models.CharField(default='null', max_length=200)),
                ('receiver', models.CharField(default='null', max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default='2020-12-15 15:05:36.715175')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Week_no', models.IntegerField(blank=True)),
                ('Week_startdate', models.DateField(auto_now=True)),
                ('Week_enddate', models.DateField(auto_now=True)),
                ('Revision_no', models.CharField(default='null', max_length=255)),
                ('Letter_refno', models.CharField(default='null', max_length=255)),
                ('Letter_date', models.DateField(auto_now=True)),
                ('Payment_date', models.DateField(auto_now=True)),
                ('Disbursement_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Lc_date', models.DateField(auto_now=True)),
                ('Interest_levydate', models.DateField(auto_now=True)),
                ('Entity', models.CharField(blank=True, default='null', max_length=255)),
                ('DevAdditional', models.BigIntegerField(blank=True)),
                ('DevAdditionalSignChange', models.BigIntegerField(blank=True)),
                ('DevPostfacto', models.BigIntegerField(blank=True)),
                ('DevNormal', models.BigIntegerField(blank=True)),
                ('DevFinal', models.BigIntegerField(blank=True)),
                ('Outstandings', models.BigIntegerField(blank=True, default=0)),
                ('Status', models.CharField(default='Notified', max_length=100)),
                ('PayableorReceivable', models.CharField(blank=True, default='null', max_length=25)),
                ('image_url', models.URLField(default='null')),
                ('is_entered_payment', models.BooleanField(default=False)),
                ('modified_remarks', models.CharField(default='null', max_length=255)),
                ('registration_id', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=20)),
                ('weekno', models.CharField(default=None, max_length=20)),
                ('disbursed_date', models.DateField(blank=True, default=None)),
            ],
            options={
                'db_table': 'DisbursedDate',
            },
        ),
        migrations.CreateModel(
            name='DSMDuePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2020-2021', max_length=10)),
                ('from_year', models.CharField(max_length=10, null=True)),
                ('to_year', models.CharField(max_length=10, null=True)),
                ('actual_weekno', models.CharField(max_length=10, null=True)),
                ('considered_weekno', models.CharField(max_length=10, null=True)),
                ('dueinpool', models.BigIntegerField(blank=True)),
                ('transdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiscPaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, default='null', max_length=15)),
                ('Week', models.CharField(blank=True, default='null', max_length=15)),
                ('Pay_type', models.CharField(blank=True, max_length=15)),
                ('Pay_refno', models.CharField(blank=True, max_length=100)),
                ('Pay_date', models.DateField(blank=True)),
                ('Pay_amount', models.BigIntegerField(blank=True)),
                ('Paid_by', models.CharField(default='null', max_length=250)),
                ('Paid_for', models.CharField(default='null', max_length=250)),
                ('Remarks', models.CharField(default='null', max_length=100)),
                ('isConsideredInBilling', models.BooleanField(default=False)),
                ('registration_id', models.CharField(default='SRADMIN', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MOEmployeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(default=None, max_length=50)),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
                ('designation', models.CharField(default=None, max_length=100)),
                ('contact_number', models.BigIntegerField(blank=True, default=None)),
                ('image_url', models.URLField(default=None)),
                ('registration_id', models.CharField(default='SRADMIN', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SRPCFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2020-21', max_length=50)),
                ('weekNo', models.CharField(default='1', max_length=50)),
                ('image_url', models.URLField(default='null')),
            ],
            options={
                'db_table': 'SRPC_Files',
            },
        ),
        migrations.CreateModel(
            name='UniqueState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200)),
                ('registration_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YearCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2020-21', max_length=20)),
                ('weekno', models.CharField(default='null', max_length=20)),
                ('Week_startdate', models.DateField(blank=True, default='null')),
                ('Week_enddate', models.DateField(blank=True, default='null')),
                ('srpc_date', models.DateField(blank=True, default='null')),
                ('due_date', models.DateField(blank=True, default='null')),
                ('disbursement_date', models.DateField(blank=True, default='null')),
            ],
            options={
                'db_table': 'YearCalendar',
            },
        ),
        migrations.CreateModel(
            name='TempDisburseDataPreviousWeeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disburseamount', models.BigIntegerField(blank=True)),
                ('duetopool', models.BigIntegerField(blank=True)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyUpload.ConfigureModel')),
            ],
        ),
        migrations.CreateModel(
            name='TempDisburseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disburseamount', models.BigIntegerField(blank=True)),
                ('duetopool', models.BigIntegerField(blank=True)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyUpload.ConfigureModel')),
            ],
        ),
        migrations.CreateModel(
            name='SurchargeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=10)),
                ('month', models.CharField(default=None, max_length=10)),
                ('srpc_duedate', models.DateField(default=None)),
                ('devfinal', models.BigIntegerField(blank=True, default=None)),
                ('paid_date', models.DateField(default=None)),
                ('paid_amount', models.BigIntegerField(blank=True, default=None)),
                ('calinterest', models.BigIntegerField(blank=True, default=None)),
                ('Status', models.CharField(default='Notified', max_length=50)),
                ('isConsideredInBilling', models.BooleanField(default=True)),
                ('actual_paid_date', models.DateField(blank=True, default=None)),
                ('reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyUpload.ConfigureModel')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_type', models.CharField(blank=True, max_length=15)),
                ('Pay_refno', models.CharField(blank=True, max_length=100)),
                ('Pay_date', models.DateField(blank=True)),
                ('Pay_amount', models.BigIntegerField(blank=True)),
                ('Dev_final', models.BigIntegerField(blank=True)),
                ('Due_amount', models.BigIntegerField(blank=True, default=0)),
                ('Paid_by', models.CharField(default='null', max_length=250)),
                ('Paid_for', models.CharField(default='null', max_length=250)),
                ('Remarks', models.CharField(default='null', max_length=100)),
                ('Status', models.CharField(default='Created', max_length=50)),
                ('reject_remarks', models.CharField(default='Null', max_length=255)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyUpload.ConfigureModel')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReceiveDisburse1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disburseamount', models.BigIntegerField(blank=True)),
                ('disbursedate', models.DateField(auto_now=True)),
                ('duetopool', models.BigIntegerField(blank=True)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyUpload.ConfigureModel')),
            ],
        ),
        migrations.CreateModel(
            name='FinalPayDisburse1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2020-21', max_length=20)),
                ('weekno', models.CharField(default='null', max_length=20)),
                ('actual_weekno', models.CharField(default='null', max_length=20)),
                ('pay_constituent', models.CharField(default='null', max_length=150)),
                ('devfinal', models.BigIntegerField(blank=True)),
                ('paymentdate', models.DateField(auto_now=True)),
                ('amountpaid', models.BigIntegerField(blank=True)),
                ('outstanding', models.BigIntegerField(blank=True)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeeklyUpload.ConfigureModel')),
            ],
        ),
    ]
