# Generated by Django 3.0.6 on 2020-12-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0002_auto_20201215_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2020-12-15 15:07:04.978431'),
        ),
    ]
