# Generated by Django 3.0.6 on 2020-12-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0003_auto_20201215_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalpaydisburse1',
            name='actual_weekno',
        ),
        migrations.AddField(
            model_name='configuremodel',
            name='Consider_Week_no',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2020-12-16 10:14:55.957558'),
        ),
    ]
