# Generated by Django 3.0.6 on 2020-12-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0004_auto_20201216_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2020-12-16 10:16:21.707806'),
        ),
    ]
