# Generated by Django 3.0.6 on 2020-12-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0005_auto_20201216_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsmduepool',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='dsmduepool',
            name='to_year',
        ),
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2020-12-23 14:20:18.695581'),
        ),
    ]
