# Generated by Django 3.0.6 on 2020-12-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0006_auto_20201223_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsmduepool',
            name='from_year',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='dsmduepool',
            name='to_year',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2020-12-23 14:21:39.265107'),
        ),
    ]
