# Generated by Django 3.0.6 on 2020-12-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0007_auto_20201223_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2020-12-23 14:22:19.330868'),
        ),
    ]
