# Generated by Django 3.0.6 on 2020-12-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0008_auto_20201223_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miscpaymentstatus',
            name='isConsideredInBilling',
        ),
        migrations.AddField(
            model_name='miscpaymentstatus',
            name='Actual_Week',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2020-12-29 13:01:39.380267'),
        ),
    ]
