# Generated by Django 3.1.5 on 2021-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0010_auto_20201229_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2021-01-07 11:07:11.182232'),
        ),
        migrations.AlterField(
            model_name='dsmduepool',
            name='year',
            field=models.CharField(default='2021-2022', max_length=10),
        ),
    ]
