# Generated by Django 3.1.5 on 2021-01-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0011_auto_20210107_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2021-01-23 13:06:08.524383'),
        ),
    ]
