# Generated by Django 3.1.5 on 2021-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0013_auto_20210224_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2021-03-03 12:37:46.032111'),
        ),
    ]
