# Generated by Django 3.1.5 on 2021-03-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0014_auto_20210303_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2021-03-04 12:08:14.761933'),
        ),
    ]
