# Generated by Django 3.1.5 on 2021-03-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0018_auto_20210304_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2021-03-05 10:53:01.382550'),
        ),
    ]
