# Generated by Django 3.1.5 on 2021-03-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0021_auto_20210305_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2021-03-05 11:55:10.418989'),
        ),
    ]
