# Generated by Django 3.1.5 on 2021-03-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0022_auto_20210305_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2021-03-05 14:57:41.837307'),
        ),
    ]
