# Generated by Django 3.1.5 on 2021-03-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklyUpload', '0024_auto_20210306_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatallmessages',
            name='timestamp',
            field=models.DateTimeField(default='2021-03-08 14:05:56.093592'),
        ),
    ]
